version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - PORT=8080
      - EMAIL=test@example.com
      - DB_URI=mongodb://mongodb:27017/
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_LOGIN=your_email@gmail.com
      - SMTP_PASSWORD=your_password
      - SMTP_EMAIL=your_email@gmail.com
      - SMTP_NAME=user